apiVersion: apps/v1
kind: Deployment
metadata:
  name: [[forms[0].name]]-deployment
spec:
  replicas: [[forms[0].replicas]]
  selector:
    matchLabels:
      deployment: [[forms[0].name]]
  template:
    metadata:
      labels:
        deployment: [[forms[0].name]]
    spec:
      containers:
        - name: [[forms[0].name]]-container
          image: [[forms[0].image]]
          ports:
            - containerPort: [[forms[0].targetPort]]
          securityContext:
              runAsUser: 2000
          envFrom:
            - configMapRef:
              name: [[forms[0].name]]-config
[[forms[0].command ? `          command: ${JSON.stringify(forms[0].command)}` : '']]
