apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomization

commonLabels:
  monokle: kustomize-demo

namespace: [[forms[0].namespace]]

resources:
  - [[forms[0].name]]-deployment.yaml
  - [[forms[0].name]]-service.yaml
  - [[forms[0].name]]-config.yaml
