apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: monokle-demo

commonLabels:
  monokle: kustomize-demo

namespace: [[forms[0].namespace]]

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
