apiVersion: v1
kind: Service
metadata:
  name: [[forms[0].name]]-service
spec:
  selector:
    deployment: [[forms[0].name]]
  type: NodePort
  ports:
    - port: [[forms[0].servicePort]]
      protocol: TCP
      targetPort: [[forms[0].targetPort]]
